// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqjjoucyjrwnnpaazruf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxampvdWN5anJ3bm5wYWF6cnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTg1MDksImV4cCI6MjA2OTE5NDUwOX0.7cuTbN0ihmGFlBVsoA9Ccez-ZdIo3PjvmnACR-T91cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});